
#include <linux/netlink.h>

#define EIGRP_PROT_NUM 88

//METRIC CONSTANTS
#define EIGRP_BANDWIDTH		10000000
#define EIGRP_DELAY_PICO	1000000
#define EIGRP_INACCESSIBLE	0xFFFFFFFFFFFFFFFFLL
#define EIGRP_MAX_HOPS		100
#define EIGRP_CLASSIC_SCALE	256
#define EIGRP_WIDE_SCALE	65536
#define EIGRP_RIB_SCALE		128

#define EIGRP_UNREACHABLE	0xFFFFFFFF

//ROUTING TABLE CONSTANTS

#define PACKET_LEN 2500

